### ISSUE TITLE
Uncaught ReferenceError: ForceGraph3D is not defined

### ISSUE THREAD

**Issue by kristianmandrup** [vasturiano/d3-force-3d#1]
Having just forked the repo and copied the Miserable example from [bl.ocks.org/vasturiano](https://bl.ocks.org/vasturiano/f59675656258d3f490e9faa40828c0e7)

I run a local file server using [serve](https://www.npmjs.com/package/serve) and have everything configured as it should. I even encapsulated the `index.js` code in a `drawGraph` function:

```js
function drawGraph() {
  const Graph = ForceGraph3D()
    (document.getElementById("3d-graph"));

  // ...
}

So I could use a callback  `document.addEventListener("DOMContentLoaded", cb)` to make sure that the DOM and all script dependencies are loaded before attempting to draw the graph.

```html
  <script src="index.js"></script>
  <script>
    document.addEventListener("DOMContentLoaded", function (event) {
      console.log("DOM fully loaded and parsed");
      drawGraph();
    });
  </script>
```

However, when searching for `ForceGraph3D` in the entire project, I find no match. What am I missing? I presume the example on your blog is out of date?

Please advice. Thanks.

**Comment by kristianmandrup** [comment]
PS: My fork/changes can be found [here](https://github.com/kristianmandrup/d3-force-3d/commit/1be7335b9ef60b07306d15049febf1a909800a82)

**Comment by kristianmandrup** [comment]
Googling `ForceGraph3D` turned up the [3d-force-graph](https://github.com/vasturiano/3d-force-graph) library, so I guess I'd have to add that as a dependency then...

**Comment by kristianmandrup** [comment]
Now I get a failure to load the JSON file for the miserables data:

`:5000/miserables/.miserables.json Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by kristianmandrup** [comment]
Ah, I finally found it [here](https://raw.githubusercontent.com/d3/d3-plugins/master/graph/data/miserables.json)

**Comment by kristianmandrup** [comment]
Unfortunately miserables data comes invarious formats, and your `data-set-loader.js` also requires a `.blocks.json` file. Where can I get these sample data or formats that seem to be used in many of the d3 force graph examples?? Cheers.

**Comment by vasturiano** [comment]
@kristianmandrup it seems like you may be looking for the [3d-force-graph](https://github.com/vasturiano/3d-force-graph) library instead.
This library (d3-force-3d) is just the force directed layout.

The [examples folder](https://github.com/vasturiano/3d-force-graph/tree/master/example) is a good place to start. It also includes the datasets folder you're looking for.

**Comment by kristianmandrup** [comment]
Ah sweet :) Exactly! Would be awesome if you could update the Readme and/or blog post to include these pointers ;) Thanks!
