### ISSUE TITLE
lost link to an example

### ISSUE THREAD

**Issue by jaygray0919** [vasturiano/d3-force-3d#13]
One of your developers implemented a `les mis` version with a person-selector to feature just the person-relationships.
The issue where I found the example is closed.
The example uses two `size` values (11 for the number of groups and 55 - which we do not understand)
It also uses `type: person` which may be part of the technique to set the person-selector.
Can you point me to the issue that featured the customized version?
I would like to ask the developer an implementation question.

**Comment by vasturiano** [comment]
@jaygray0919 it's not clear to me how your request relates to this repo, but you can always browse the list of closed issues on github: https://github.com/vasturiano/d3-force-3d/issues?q=

**Comment by jaygray0919** [comment]
this is the example i was looking for:
  https://github.com/vasturiano/3d-force-graph/issues/225
