### ISSUE TITLE
Currently shipping ES6 syntax

### ISSUE THREAD

**Issue by litinskii** [vasturiano/d3-force-3d#5]
At the moment, d3-force-3d is shipping ES6 syntax as per [here](https://github.com/vasturiano/d3-force-3d/blob/master/src/link.js#L60).

Because d3-force-3d isn't transpiled, this is breaking IE11 and other older browsers.
The arrow function crashes build on IE 11. 
Changed arrow function to regular function or update rollup configs ?

**Comment by vasturiano** [comment]
@litinskii you are right that it's shipping ES6 syntax. `d3-force-3d` is a fork of `d3-force` and the syntax is inherited from there, so this concern should be handled upstream. There is an issue raised there which explains the motivation: https://github.com/d3/d3-force/issues/134

**Comment by litinskii** [comment]
@vasturiano Ah ((( Thanks for the explanation
